### ISSUE TITLE
Clientside Ability GUIs, Serverside execution

### ISSUE THREAD

**Issue by cmkrist** [OpenChamp/_original_client#40]
Clientside abilities should trigger the GUI without prompting the server, but the server should verify that they can cast an ability and render them to the clients.

None of this is syncing as of now

**Comment by Humungus-Fungus** [comment]
Fixed in #52

**Comment by noah1510** [comment]
The server side ability checks are now in place.
The new implementation of abilities uses a multiplayer spawner for the ability projectile, so that should sync the projectiles to all the clients automatically.
